#!/usr/bin/env python3
"""Generate ``engine_stages.json`` from agent-engine's own workflow sources.

``seed_all_agents.py``'s docstring has always said this file is generated by
"walking every ``wf.step.code``/``.agent``/``.gate`` call". It described a
script that was never committed, so in practice the stage list was produced by
hand once and drifted -- which is the exact failure that docstring warns about.
This is that script.

It reads four things out of each workflow and nothing else, so the output is
derived rather than authored:

* the IDS of the ``wf.step.*`` calls -- the stage list,
* which of the three primitives each used -- the stage ``kind``,
* for an ``.agent`` call, the ``skillRef`` of the agent class it runs -- which
  is what lets the Studio put the right prompt next to the right stage,
* for an ``.agent`` call, the agent class's own ``config.id`` and its compiled
  ``modelPolicy`` (model and vendor) -- ``agent_id``, ``default_model`` and
  ``vendor`` on the stage. The engine keys a Studio's per-stage model override
  by ``config.id``, not by the step id, and the Studio can only say what
  "engine default" means for a stage if it knows the compiled model. Both were
  missing from the first version of this feature, which is how a per-stage pick
  was stored, displayed and never applied, under a label that said every stage
  ran on Sonnet.

## Why skillRef has to be resolved rather than read

A workflow step id and its agent's own id are different names for different
things: ``wf.step.agent("10-draft-post", draftAgent, ...)`` runs
``XDraftAgent``, whose config says ``skillRef: "x-draft@1"``. The step id is
where it sits in the run; the skillRef is which prompt it loads. So resolution
is three hops -- step id, to the variable, to the class, to its skillRef --
and they live in different files.

## Deliberately not a TypeScript parser

Regex over source is usually the wrong tool and is the right one here for one
reason: the alternative is this Python service shelling out to the TypeScript
compiler over another repository. The patterns are narrow, each matches a
convention this codebase follows without exception, and ``--check`` fails
loudly when a workflow stops matching rather than silently emitting a short
list.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from functools import lru_cache
from pathlib import Path
from typing import Any

#: agent-engine sits beside this repository in every environment this runs in.
DEFAULT_ENGINE_ROOT = Path(__file__).resolve().parents[2] / "agent-engine"
OUT_FILE = Path(__file__).with_name("engine_stages.json")

#: The step id is always the first argument and always built from a literal —
#: a computed one would break the durable store's own checkpoint keys. Since
#: 2026-09 most workflows wrap the literal in one to three pure-suffix helpers
#: (`rev("id")` adds `-r1` on a revision round, `att("id")` adds
#: `-attempt-2`, `id(att("09-draft-post"))` both), so the literal is found
#: through up to three call wrappers. Anything else the helper adds is a
#: suffix on the same stage, never a different stage.
WRAPPERS = r"(?:\w+\(\s*){0,3}"
STEP_CALL = re.compile(r"wf\.step\.(code|agent|gate)\(\s*" + WRAPPERS + r"[\"'`]([^\"'`$]+)[\"'`]")

#: A templated id, e.g. `05-write-copy-attempt-${attempt}`: one stage a
#: workflow may run several times, not several stages.
TEMPLATED_CALL = re.compile(r"wf\.step\.(code|agent|gate)\(\s*" + WRAPPERS + r"`([^`$]*)\$\{")

#: `stepId.replace("03s-script", "03u-script")`, bare or inside a template
#: literal: the model step tiktok-agent runs INSIDE its code step, under the
#: replaced id. The replacement is the id that appears in a run's trace.
REPLACE_CALL = re.compile(
    r"wf\.step\.(code|agent|gate)\(\s*`?(?:\$\{)?\s*\w+\.replace\(\s*\"[^\"]+\",\s*\"([^\"]+)\"\s*\)"
)

#: `const draftAgent = new XDraftAgent({...})`
AGENT_BINDING = re.compile(r"const\s+(\w+)\s*=\s*new\s+(\w+)\s*\(")

#: The agent an `.agent` call runs — either a variable or constructed inline.
#: The id argument may itself contain commas (`stepId.replace("a", "b")`), so
#: the second argument is found by `second_argument`, not by a regex on `[^,]+`.
AGENT_CALL_OPEN = re.compile(r"wf\.step\.agent\(")
AGENT_IDENT = re.compile(r"\s*(?:new\s+(\w+)|(\w+))")


def second_argument(text: str, open_paren: int) -> int | None:
    """Index just past the first top-level comma after `open_paren`, or None."""
    depth = 0
    quote: str | None = None
    i = open_paren + 1
    while i < len(text):
        ch = text[i]
        if quote is not None:
            if ch == "\\":
                i += 2
                continue
            if ch == quote:
                quote = None
        elif ch in "\"'`":
            quote = ch
        elif ch in "([{":
            depth += 1
        elif ch in ")]}":
            if depth == 0:
                return None
            depth -= 1
        elif ch == "," and depth == 0:
            return i + 1
        i += 1
    return None


SKILL_REF = re.compile(r"skillRef:\s*\"([^\"]+)\"")

#: A human gate declared through the shared review-cycle primitive:
#:
#:     runReviewCycle(wf, { gateId: "15-batch-review", ..., buildGate: ... })
#:
#: The primitive itself calls `wf.step.gate(`${options.gateId}-r${revision}`)`
#: from packages/workflow, so STEP_CALL never sees it: the literal part of that
#: template is empty, and the call is not in any agent's source anyway. Six
#: agents declare their only human gate this way, and before this pattern
#: existed all six reported no gates at all.
REVIEW_CYCLE_GATE = re.compile(r"gateId:\s*\"([^\"]+)\"")

#: The `kind` a gate carries -- `batch_review`, `prompt_set_review`,
#: `landing_craft_review`, and five more. Read from the first `kind:` after the
#: gate is opened, which is where every one of them sits.
GATE_KIND = re.compile(r"kind:\s*\"([a-z_]+)\"")

#: Where a review-cycle gate's `kind` actually lives. `gateId` and `buildGate`
#: are properties of the same object, but not adjacent ones: `attempt` sits
#: between them and instagram-agent's runs to hundreds of lines, so a fixed
#: window from `gateId` finds nothing. Anchoring on `buildGate` instead is
#: exact rather than merely wider.
BUILD_GATE = re.compile(r"buildGate:")

#: `id: "x-draft"` -- the agent class's own step id (`AgentStepConfig.id`),
#: which is what `applyStageModelOverride` looks a stage override up by. A
#: constant (`id: INTEL_REPORT_DRAFT_STEP_ID`) is resolved in the package.
AGENT_CONFIG_ID = re.compile(r"\bid:\s*(?:\"([^\"]+)\"|([A-Z][A-Z0-9_]+))")
#: `modelPolicy: resolveModelPolicy("x-draft", { policy: "pinned", model: "...", vendor: "..." })`
MODEL_POLICY_CALL = re.compile(
    r"modelPolicy:\s*resolveModelPolicy\(\s*[^,]+,\s*\{([^}]*)\}", re.DOTALL
)
#: `modelPolicy: { policy: "commodity", model: "claude-haiku-4-5-20251001" }`
MODEL_POLICY_LITERAL = re.compile(r"modelPolicy:\s*\{([^}]*)\}", re.DOTALL)
#: `modelPolicy: INTEL_REPORT_DRAFT_MODEL_POLICY,` -- a named constant, resolved in the package.
MODEL_POLICY_CONST = re.compile(r"modelPolicy:\s*([A-Z][A-Z0-9_]+)\s*[,}]")
#: The `model:` field inside a policy object: a literal, or a constant such as
#: `REPUTATION_CLASSIFIER_MODEL_ID`.
MODEL_FIELD = re.compile(r"\bmodel:\s*(?:\"([^\"]+)\"|([A-Z][A-Z0-9_]+))")
VENDOR_FIELD = re.compile(r"\bvendor:\s*\"([^\"]+)\"")
#: The engine's default when a policy names no vendor (`resolveModelVendor`).
DEFAULT_ENGINE_VENDOR = "anthropic"

#: Step ids the SHARED terminal guardrail contributes (packages/workflow's
#: `runTopicGuardrail`). Identifiers, not prompt text: the guardrail builds its
#: system prompt inline from the client's own forbidden-topic list, so it has
#: no skillRef and nothing for the Studio to edit. Listed here because they
#: come from shared code rather than from any one workflow's source.
GUARDRAIL_STEPS = [("guardrail-verify-load-topics", "code"), ("guardrail-verify", "agent")]


#: `case "x-agent": return createXAgentWorkflow(deps)` — the engine's own
#: product-to-workflow mapping, and the only place that association exists.
#: Keying off directory names instead was wrong twice over: one package can
#: hold two products (setup-agents) and one can hold a second, unrelated
#: workflow (branded-shorts' style-exploration onboarding).
PRODUCT_CASE = re.compile(
    r"case\s+\"([a-z0-9-]+)\":\s*\{?\s*(?:.*?)return\s+(create\w+)\(", re.DOTALL
)

WIRING_FILE = ("apps", "agent-server", "src", "wiring", "workflows.ts")


def gate_kind_after(text: str, pos: int, window: int = 400) -> str:
    """The gate's ``kind``, read from just after the gate is opened.

    A window rather than a full parse: a direct ``wf.step.gate`` call puts
    ``kind`` on the very next line, and 400 characters is comfortably past that
    while stopping well short of the next step. A miss costs the ``gate_kind``
    field and never the gate itself.
    """

    match = GATE_KIND.search(text, pos, pos + window)
    return match.group(1) if match else ""


def review_cycle_gate_kind(text: str, pos: int) -> str:
    """The ``kind`` inside the ``buildGate`` belonging to one ``gateId``.

    Bounded by the NEXT ``gateId`` rather than by a character count: if another
    review cycle starts before this one's ``buildGate`` is found, the two are
    not related and guessing would attribute one agent's gate kind to another.
    """

    limit = REVIEW_CYCLE_GATE.search(text, pos)
    end = limit.start() if limit else len(text)
    build = BUILD_GATE.search(text, pos, end)
    if not build:
        return ""
    return gate_kind_after(text, build.end())


def collapse_retry_suffix(step_id: str) -> str:
    """`05-write-copy-attempt-1` and `05-write-copy-attempt-` -> `05-write-copy`.

    A templated id contributes only its literal prefix, so the trailing
    `-attempt-` arrives without a number. Both forms are one stage a workflow
    may run several times, never several stages.
    """
    trimmed = re.sub(r"-attempt-?\d*$", "", step_id)
    return trimmed.rstrip("-")


def order_key(step_id: str) -> tuple[float, str]:
    """Recovers a step's intended position from its own `NN-` prefix.

    Mirrors agent-engine's own `stepOrderKey` in `apps/agent-server/src/report.ts`
    — the same convention every step id in that repo follows.
    """
    match = re.match(r"^(\d+)", step_id)
    return (float(match.group(1)) if match else float("inf"), step_id)


@lru_cache(maxsize=1)
def agent_sources(engine_root: Path) -> tuple[tuple[Path, str], ...]:
    """Every agent source file in the engine, read once.

    Read once because it used to be read sixteen times. ``factory_source``
    rescanned and re-read all 421 files for each of the fifteen products, so a
    run cost roughly 6,300 file opens plus fifteen directory walks -- around two
    minutes over a network-backed checkout, which is long enough that the
    generator stopped being something anyone ran casually. One pass is about ten
    seconds, and a generator people run is worth more than one they avoid.
    """

    out: list[tuple[Path, str]] = []
    for path in sorted((engine_root / "agents").rglob("*.ts")):
        if "__tests__" in path.parts or "dist" in path.parts:
            continue
        out.append((path, path.read_text(encoding="utf-8", errors="replace")))
    return tuple(out)


def class_skill_refs(engine_root: Path) -> dict[str, str]:
    """Every agent class in the engine mapped to the skillRef it declares."""
    refs: dict[str, str] = {}
    for _path, text in agent_sources(engine_root):
        for match in re.finditer(r"class\s+(\w+)\s+extends\s+BaseAgent", text):
            # The whole remainder of the file, not a fixed window: a drafting
            # step's config carries a version-history comment that runs to
            # several thousand characters before `skillRef`, and a 2,000-char
            # window silently dropped the skillRef of every such step.
            tail = text[match.end() :]
            ref = SKILL_REF.search(tail)
            if ref:
                refs[match.group(1)] = ref.group(1)
    return refs


def _policy_from_fields(fields: str, package_text: str) -> dict[str, str] | None:
    """`{model, vendor}` from the inside of a policy object literal, or None."""
    model_match = MODEL_FIELD.search(fields)
    if not model_match:
        return None
    model = model_match.group(1)
    if model is None:
        # `model: SOME_CONSTANT` -- resolve the string constant in the package.
        const_match = re.search(
            rf"const\s+{re.escape(model_match.group(2))}\s*=\s*\"([^\"]+)\"", package_text
        )
        if not const_match:
            return None
        model = const_match.group(1)
    vendor_match = VENDOR_FIELD.search(fields)
    return {
        "model": model,
        "vendor": vendor_match.group(1) if vendor_match else DEFAULT_ENGINE_VENDOR,
    }


def _policy_from_text(text: str, package_text: str) -> dict[str, str] | None:
    """The compiled model policy declared in `text`, following one named constant.

    The EARLIEST `modelPolicy:` in `text` wins, whichever shape it takes: a
    file that declares two agent classes must not have the second class's
    call-shaped policy read as the first class's, just because the call shape
    was tried before the constant shape.
    """
    candidates = [
        m
        for m in (
            MODEL_POLICY_CALL.search(text),
            MODEL_POLICY_LITERAL.search(text),
            MODEL_POLICY_CONST.search(text),
        )
        if m
    ]
    if not candidates:
        return None
    first = min(candidates, key=lambda m: m.start())
    if first.re is MODEL_POLICY_CALL or first.re is MODEL_POLICY_LITERAL:
        return _policy_from_fields(first.group(1), package_text)
    const = first
    if const:
        name = re.escape(const.group(1))
        definition = re.search(
            rf"const\s+{name}\b[^=]*=\s*(?:resolveModelPolicy\(\s*[^,]+,\s*)?\{{([^}}]*)\}}",
            package_text,
            re.DOTALL,
        )
        if definition:
            return _policy_from_fields(definition.group(1), package_text)
    return None


def _resolve_agent_id(id_match: re.Match[str], package_text: str) -> str | None:
    """The literal id, or the string a constant such as `INTEL_REPORT_DRAFT_STEP_ID` holds."""
    if id_match.group(1):
        return id_match.group(1)
    const_match = re.search(
        rf"const\s+{re.escape(id_match.group(2))}\s*=\s*\"([^\"]+)\"", package_text
    )
    return const_match.group(1) if const_match else None


def shared_guardrail_policy(engine_root: Path) -> dict[str, str] | None:
    """`{agent_id, default_model, vendor}` of the shared terminal guardrail's judge.

    Lives in `packages/workflow`, not under any one agent, so `class_model_policies`
    never sees it; read the same way so the Studio can say what `guardrail-verify`
    runs on (Haiku, by design: the cheapest catalogued Claude for a yes/no check).
    """
    path = engine_root / "packages" / "workflow" / "src" / "primitives" / "topic-guardrail.ts"
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8", errors="replace")
    # The id constant (`GUARDRAIL_STEP_ID`) lives in packages/core's agent
    # definitions, so constants resolve against both packages' sources.
    package_text = "\n".join(
        p.read_text(encoding="utf-8", errors="replace")
        for package in ("workflow", "core")
        for p in (engine_root / "packages" / package / "src").rglob("*.ts")
        if "__tests__" not in p.parts
    )
    id_match = AGENT_CONFIG_ID.search(text)
    policy = _policy_from_text(text, package_text)
    agent_id = _resolve_agent_id(id_match, package_text) if id_match else None
    if not agent_id or not policy:
        return None
    return {"agent_id": agent_id, "default_model": policy["model"], "vendor": policy["vendor"]}


def class_model_policies(engine_root: Path) -> dict[str, dict[str, str]]:
    """Every agent class mapped to `{agent_id, default_model, vendor}`.

    Read from the class body first (the common shape: `config` declared inline
    with `id:` and `modelPolicy:`), then from the whole file (intel-report
    declares its config as a module-level literal the class spreads), with
    named constants resolved across the package's `src/`. A class this cannot
    read is reported and omitted rather than guessed at: a stage with no
    `default_model` renders as "not extracted" in the Studio, which is true,
    where a guess would be a decision nobody made.
    """
    policies: dict[str, dict[str, str]] = {}
    for path in (engine_root / "agents").rglob("*.ts"):
        if "__tests__" in path.parts or "dist" in path.parts:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        classes = list(re.finditer(r"class\s+(\w+)\s+extends\s+BaseAgent", text))
        if not classes:
            continue
        src_dir = path.parent.parent if path.parent.name == "agent" else path.parent
        package_text = "\n".join(
            p.read_text(encoding="utf-8", errors="replace")
            for p in src_dir.rglob("*.ts")
            if "__tests__" not in p.parts and "dist" not in p.parts
        )
        for index, match in enumerate(classes):
            # The class body runs to the next class in the file, not to a
            # fixed window: a window long enough for a drafting step's
            # version-history comment also reaches into the next class.
            body_end = classes[index + 1].start() if index + 1 < len(classes) else len(text)
            body = text[match.end() : body_end]
            id_match = AGENT_CONFIG_ID.search(body) or AGENT_CONFIG_ID.search(text)
            policy = _policy_from_text(body, package_text) or _policy_from_text(text, package_text)
            agent_id = _resolve_agent_id(id_match, package_text) if id_match else None
            if not agent_id or not policy:
                print(
                    f"  ! {path.name}: could not read {match.group(1)}'s config id / "
                    "modelPolicy -- "
                    "its stage will carry no default_model",
                    file=sys.stderr,
                )
                continue
            policies[match.group(1)] = {
                "agent_id": agent_id,
                "default_model": policy["model"],
                "vendor": policy["vendor"],
            }
    return policies


def product_factories(engine_root: Path) -> dict[str, str]:
    """Product id -> the workflow factory the engine dispatches it to."""
    text = (engine_root.joinpath(*WIRING_FILE)).read_text(encoding="utf-8")
    body = text[text.index("switch (productId)") :] if "switch (productId)" in text else text
    return {product: factory for product, factory in PRODUCT_CASE.findall(body)}


def factory_source(engine_root: Path, factory: str) -> Path | None:
    """The file that exports one workflow factory."""
    needle = f"export function {factory}("
    for path, text in agent_sources(engine_root):
        if needle in text:
            return path
    return None


def stages_for_workflow(
    path: Path,
    refs: dict[str, str],
    policies: dict[str, dict[str, str]] | None = None,
    guardrail: dict[str, str] | None = None,
) -> list[dict[str, Any]]:
    """Every stage ONE workflow runs, in run order, with skillRefs where they exist.

    Scoped to the single file that exports the factory, not the whole package
    directory: branded-shorts keeps its Style Exploration onboarding beside its
    main pipeline, and scanning the directory merged the two into one 24-stage
    fiction.
    """
    found: dict[str, dict[str, Any]] = {}
    skipped_dynamic: set[str] = set()

    text = path.read_text(encoding="utf-8", errors="replace")

    # Bindings WITH positions, because a flat name->class map is wrong when
    # a name is reused: tiktok-agent constructs both its agents into a
    # variable called `agent`, so a flat map made 03a-moment resolve to
    # tiktok-commentary. The binding that applies is the nearest one
    # ABOVE the call.
    bindings = [(m.start(), m.group(1), m.group(2)) for m in AGENT_BINDING.finditer(text)]

    def agent_class_at(pos: int, var: str, inline: str) -> str:
        if inline:
            return inline
        candidates = [cls for at, name, cls in bindings if name == var and at < pos]
        return candidates[-1] if candidates else ""

    agent_calls: dict[int, str] = {}
    for m in AGENT_CALL_OPEN.finditer(text):
        after_id = second_argument(text, m.end() - 1)
        if after_id is None:
            continue
        ident = AGENT_IDENT.match(text, after_id)
        if ident:
            agent_calls[m.start()] = agent_class_at(
                m.start(), ident.group(2) or "", ident.group(1) or ""
            )

    calls = [(m.start(), m.group(1), m.group(2)) for m in STEP_CALL.finditer(text)]
    calls += [(m.start(), m.group(1), m.group(2)) for m in TEMPLATED_CALL.finditer(text)]
    calls += [(m.start(), m.group(1), m.group(2)) for m in REPLACE_CALL.finditer(text)]
    for _pos, kind, raw_id in sorted(calls):
        step_id = collapse_retry_suffix(raw_id)
        if not step_id:
            continue
        # A genuinely computed id, e.g. `06${"bd"[tierIndex-1]}-${tier.id}-...`,
        # leaves only its numeric prefix behind. Emitting "06" as a stage
        # would put a label in the Studio that matches no step in any run
        # trace, which is worse than the stage being absent — the whole
        # point of showing stages is that a reader can line them up against
        # a run. Skipped loudly instead.
        if re.fullmatch(r"\d+[a-z]?", step_id):
            skipped_dynamic.add(raw_id)
            continue
        entry: dict[str, Any] = {"id": step_id, "kind": kind}
        if kind == "agent":
            cls = agent_calls.get(_pos, "")
            if refs.get(cls):
                entry["skill_ref"] = refs[cls]
            policy = (policies or {}).get(cls)
            if policy:
                entry.update(policy)
        if kind == "gate":
            entry["is_gate"] = True
            gate_kind = gate_kind_after(text, _pos)
            if gate_kind:
                entry["gate_kind"] = gate_kind

        # A GATE ALWAYS WINS over a non-gate for the same id, and that is a
        # fix rather than a preference. Four agents open their gate inside a
        # ternary whose other arm is a `code` step with the SAME id:
        #
        #     options.autoApprove
        #       ? await wf.step.code("04-batch-review", () => approve)
        #       : await wf.step.gate("04-batch-review", { kind: "batch_review" })
        #
        # The `code` arm is written first, so first-writer-wins recorded the
        # AUTO-APPROVE SHORTCUT and threw away the human gate -- the stage came
        # out as ordinary code, and a planner reading it would promise a client
        # immediate delivery from a workflow that waits 24 hours for a person.
        # The gate is the real behaviour; `autoApprove` is a test affordance.
        #
        # Below the gate rule, first writer wins but a later reading of the
        # same id may still UPGRADE it: one carrying a skillRef replaces one
        # that does not, and one that resolved the agent class merges its
        # model policy into what is already there rather than replacing it.
        # Ordered deliberately -- gate over skillRef over policy -- because
        # the three can arrive in any order and only the first is about which
        # stage this IS.
        existing = found.get(step_id)
        if existing is None:
            found[step_id] = entry
        elif entry.get("is_gate") and not existing.get("is_gate"):
            found[step_id] = entry
        elif "skill_ref" not in existing and "skill_ref" in entry:
            found[step_id] = entry
        elif "agent_id" not in existing and "agent_id" in entry:
            found[step_id] = {**existing, **entry}

    # Gates declared through the shared review-cycle primitive. Added after the
    # direct calls above so an id already recorded as a real `wf.step.gate` is
    # left alone, and never overwritten by a weaker reading of itself.
    for match in REVIEW_CYCLE_GATE.finditer(text):
        gate_id = collapse_retry_suffix(match.group(1))
        if not gate_id:
            continue
        entry = {"id": gate_id, "kind": "gate", "is_gate": True}
        gate_kind = review_cycle_gate_kind(text, match.end())
        if gate_kind:
            entry["gate_kind"] = gate_kind
        current = found.get(gate_id)
        if current is None or not current.get("is_gate"):
            found[gate_id] = entry

    if "runTopicGuardrail(" in text:
        for gid, gkind in GUARDRAIL_STEPS:
            found.setdefault(gid, {"id": gid, "kind": gkind})
            if gkind == "agent" and guardrail:
                found[gid] = {**found[gid], **guardrail}

    for raw in sorted(skipped_dynamic):
        print(
            f"  ! {path.name}: step id `{raw}` is computed at run time — omitted", file=sys.stderr
        )

    return [found[k] for k in sorted(found, key=order_key)]


def generate(engine_root: Path) -> dict[str, list[dict[str, Any]]]:
    refs = class_skill_refs(engine_root)
    policies = class_model_policies(engine_root)
    guardrail = shared_guardrail_policy(engine_root)
    factories = product_factories(engine_root)
    if not factories:
        sys.exit("could not read any product->factory cases from the engine's wiring/workflows.ts")

    out: dict[str, list[dict[str, Any]]] = {}
    for product, factory in sorted(factories.items()):
        source = factory_source(engine_root, factory)
        if source is None:
            print(f"  ! {product}: no file exports {factory}() — skipped", file=sys.stderr)
            continue
        stages = stages_for_workflow(source, refs, policies, guardrail)
        if stages:
            out[product] = stages
        else:
            print(
                f"  ! {product}: {source.name} exported {factory}() but declared no steps",
                file=sys.stderr,
            )
    return out


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--engine-root", type=Path, default=DEFAULT_ENGINE_ROOT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed file differs, without writing. For CI.",
    )
    args = parser.parse_args()

    if not (args.engine_root / "agents").is_dir():
        sys.exit(f"no agents/ directory under {args.engine_root} — pass --engine-root")

    generated = generate(args.engine_root)
    rendered = json.dumps(generated, indent=2, ensure_ascii=False) + "\n"

    total = sum(len(v) for v in generated.values())
    with_refs = sum(1 for v in generated.values() for s in v if s.get("skill_ref"))
    model_steps = sum(1 for v in generated.values() for s in v if s["kind"] == "agent")
    with_models = sum(1 for v in generated.values() for s in v if s.get("default_model"))
    print(
        f"{len(generated)} agents, {total} stages, "
        f"{model_steps} model steps, {with_refs} with a skillRef, "
        f"{with_models} with a default model"
    )

    if args.check:
        current = OUT_FILE.read_text(encoding="utf-8") if OUT_FILE.is_file() else ""
        if current != rendered:
            sys.exit(
                f"{OUT_FILE.name} is stale — regenerate it with "
                "`python scripts/generate_engine_stages.py` and commit the result."
            )
        print("up to date")
        return 0

    OUT_FILE.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
